apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app-8080
  name: devops-app-8080-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: devops-app-8080
  type: LoadBalancer
