apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-app-autoscaler 
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: devops-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
